// Generated by gencpp from file cse571_project/ActionMsg.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_ACTIONMSG_H
#define CSE571_PROJECT_MESSAGE_ACTIONMSG_H

#include <ros/service_traits.h>


#include <cse571_project/ActionMsgRequest.h>
#include <cse571_project/ActionMsgResponse.h>


namespace cse571_project
{

struct ActionMsg
{

typedef ActionMsgRequest Request;
typedef ActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionMsg
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::ActionMsg > {
  static const char* value()
  {
    return "dfdaf84421aa9323fca0ea8f7917a197";
  }

  static const char* value(const ::cse571_project::ActionMsg&) { return value(); }
};

template<>
struct DataType< ::cse571_project::ActionMsg > {
  static const char* value()
  {
    return "cse571_project/ActionMsg";
  }

  static const char* value(const ::cse571_project::ActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::ActionMsgRequest> should match 
// service_traits::MD5Sum< ::cse571_project::ActionMsg > 
template<>
struct MD5Sum< ::cse571_project::ActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::ActionMsg >::value();
  }
  static const char* value(const ::cse571_project::ActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::ActionMsgRequest> should match 
// service_traits::DataType< ::cse571_project::ActionMsg > 
template<>
struct DataType< ::cse571_project::ActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::ActionMsg >::value();
  }
  static const char* value(const ::cse571_project::ActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::ActionMsgResponse> should match 
// service_traits::MD5Sum< ::cse571_project::ActionMsg > 
template<>
struct MD5Sum< ::cse571_project::ActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::ActionMsg >::value();
  }
  static const char* value(const ::cse571_project::ActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::ActionMsgResponse> should match 
// service_traits::DataType< ::cse571_project::ActionMsg > 
template<>
struct DataType< ::cse571_project::ActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::ActionMsg >::value();
  }
  static const char* value(const ::cse571_project::ActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_ACTIONMSG_H
