// Generated by gencpp from file cse571_project/CheckEdgeResponse.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_CHECKEDGERESPONSE_H
#define CSE571_PROJECT_MESSAGE_CHECKEDGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cse571_project
{
template <class ContainerAllocator>
struct CheckEdgeResponse_
{
  typedef CheckEdgeResponse_<ContainerAllocator> Type;

  CheckEdgeResponse_()
    : value(0)  {
    }
  CheckEdgeResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckEdgeResponse_

typedef ::cse571_project::CheckEdgeResponse_<std::allocator<void> > CheckEdgeResponse;

typedef boost::shared_ptr< ::cse571_project::CheckEdgeResponse > CheckEdgeResponsePtr;
typedef boost::shared_ptr< ::cse571_project::CheckEdgeResponse const> CheckEdgeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cse571_project::CheckEdgeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cse571_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const ::cse571_project::CheckEdgeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3087778e93fcd34ULL;
  static const uint64_t static_value2 = 0xcc8d65bc54e850d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cse571_project/CheckEdgeResponse";
  }

  static const char* value(const ::cse571_project::CheckEdgeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 value\n\
";
  }

  static const char* value(const ::cse571_project::CheckEdgeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckEdgeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cse571_project::CheckEdgeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cse571_project::CheckEdgeResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_CHECKEDGERESPONSE_H
