// Generated by gencpp from file cse571_project/CheckEdge.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_CHECKEDGE_H
#define CSE571_PROJECT_MESSAGE_CHECKEDGE_H

#include <ros/service_traits.h>


#include <cse571_project/CheckEdgeRequest.h>
#include <cse571_project/CheckEdgeResponse.h>


namespace cse571_project
{

struct CheckEdge
{

typedef CheckEdgeRequest Request;
typedef CheckEdgeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckEdge
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::CheckEdge > {
  static const char* value()
  {
    return "1ad13511a24e6f2f7882cfab4c1f2f18";
  }

  static const char* value(const ::cse571_project::CheckEdge&) { return value(); }
};

template<>
struct DataType< ::cse571_project::CheckEdge > {
  static const char* value()
  {
    return "cse571_project/CheckEdge";
  }

  static const char* value(const ::cse571_project::CheckEdge&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::CheckEdgeRequest> should match 
// service_traits::MD5Sum< ::cse571_project::CheckEdge > 
template<>
struct MD5Sum< ::cse571_project::CheckEdgeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::CheckEdge >::value();
  }
  static const char* value(const ::cse571_project::CheckEdgeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::CheckEdgeRequest> should match 
// service_traits::DataType< ::cse571_project::CheckEdge > 
template<>
struct DataType< ::cse571_project::CheckEdgeRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::CheckEdge >::value();
  }
  static const char* value(const ::cse571_project::CheckEdgeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::CheckEdgeResponse> should match 
// service_traits::MD5Sum< ::cse571_project::CheckEdge > 
template<>
struct MD5Sum< ::cse571_project::CheckEdgeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::CheckEdge >::value();
  }
  static const char* value(const ::cse571_project::CheckEdgeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::CheckEdgeResponse> should match 
// service_traits::DataType< ::cse571_project::CheckEdge > 
template<>
struct DataType< ::cse571_project::CheckEdgeResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::CheckEdge >::value();
  }
  static const char* value(const ::cse571_project::CheckEdgeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_CHECKEDGE_H
