// Generated by gencpp from file cse571_project/GetActions.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_GETACTIONS_H
#define CSE571_PROJECT_MESSAGE_GETACTIONS_H

#include <ros/service_traits.h>


#include <cse571_project/GetActionsRequest.h>
#include <cse571_project/GetActionsResponse.h>


namespace cse571_project
{

struct GetActions
{

typedef GetActionsRequest Request;
typedef GetActionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetActions
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::GetActions > {
  static const char* value()
  {
    return "736c654215c18c9e1fa35bdcf5f22ffa";
  }

  static const char* value(const ::cse571_project::GetActions&) { return value(); }
};

template<>
struct DataType< ::cse571_project::GetActions > {
  static const char* value()
  {
    return "cse571_project/GetActions";
  }

  static const char* value(const ::cse571_project::GetActions&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::GetActionsRequest> should match 
// service_traits::MD5Sum< ::cse571_project::GetActions > 
template<>
struct MD5Sum< ::cse571_project::GetActionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetActions >::value();
  }
  static const char* value(const ::cse571_project::GetActionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetActionsRequest> should match 
// service_traits::DataType< ::cse571_project::GetActions > 
template<>
struct DataType< ::cse571_project::GetActionsRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetActions >::value();
  }
  static const char* value(const ::cse571_project::GetActionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::GetActionsResponse> should match 
// service_traits::MD5Sum< ::cse571_project::GetActions > 
template<>
struct MD5Sum< ::cse571_project::GetActionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetActions >::value();
  }
  static const char* value(const ::cse571_project::GetActionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetActionsResponse> should match 
// service_traits::DataType< ::cse571_project::GetActions > 
template<>
struct DataType< ::cse571_project::GetActionsResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetActions >::value();
  }
  static const char* value(const ::cse571_project::GetActionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_GETACTIONS_H
