// Generated by gencpp from file cse571_project/GetInitialState.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_GETINITIALSTATE_H
#define CSE571_PROJECT_MESSAGE_GETINITIALSTATE_H

#include <ros/service_traits.h>


#include <cse571_project/GetInitialStateRequest.h>
#include <cse571_project/GetInitialStateResponse.h>


namespace cse571_project
{

struct GetInitialState
{

typedef GetInitialStateRequest Request;
typedef GetInitialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitialState
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::GetInitialState > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::cse571_project::GetInitialState&) { return value(); }
};

template<>
struct DataType< ::cse571_project::GetInitialState > {
  static const char* value()
  {
    return "cse571_project/GetInitialState";
  }

  static const char* value(const ::cse571_project::GetInitialState&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::GetInitialStateRequest> should match 
// service_traits::MD5Sum< ::cse571_project::GetInitialState > 
template<>
struct MD5Sum< ::cse571_project::GetInitialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetInitialState >::value();
  }
  static const char* value(const ::cse571_project::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetInitialStateRequest> should match 
// service_traits::DataType< ::cse571_project::GetInitialState > 
template<>
struct DataType< ::cse571_project::GetInitialStateRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetInitialState >::value();
  }
  static const char* value(const ::cse571_project::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::GetInitialStateResponse> should match 
// service_traits::MD5Sum< ::cse571_project::GetInitialState > 
template<>
struct MD5Sum< ::cse571_project::GetInitialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetInitialState >::value();
  }
  static const char* value(const ::cse571_project::GetInitialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetInitialStateResponse> should match 
// service_traits::DataType< ::cse571_project::GetInitialState > 
template<>
struct DataType< ::cse571_project::GetInitialStateResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetInitialState >::value();
  }
  static const char* value(const ::cse571_project::GetInitialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_GETINITIALSTATE_H
