// Generated by gencpp from file cse571_project/GetPossibleActions.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_GETPOSSIBLEACTIONS_H
#define CSE571_PROJECT_MESSAGE_GETPOSSIBLEACTIONS_H

#include <ros/service_traits.h>


#include <cse571_project/GetPossibleActionsRequest.h>
#include <cse571_project/GetPossibleActionsResponse.h>


namespace cse571_project
{

struct GetPossibleActions
{

typedef GetPossibleActionsRequest Request;
typedef GetPossibleActionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPossibleActions
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::GetPossibleActions > {
  static const char* value()
  {
    return "6b2bdb080846c43b9c1353f9cdd5a8a5";
  }

  static const char* value(const ::cse571_project::GetPossibleActions&) { return value(); }
};

template<>
struct DataType< ::cse571_project::GetPossibleActions > {
  static const char* value()
  {
    return "cse571_project/GetPossibleActions";
  }

  static const char* value(const ::cse571_project::GetPossibleActions&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::GetPossibleActionsRequest> should match 
// service_traits::MD5Sum< ::cse571_project::GetPossibleActions > 
template<>
struct MD5Sum< ::cse571_project::GetPossibleActionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetPossibleActions >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleActionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetPossibleActionsRequest> should match 
// service_traits::DataType< ::cse571_project::GetPossibleActions > 
template<>
struct DataType< ::cse571_project::GetPossibleActionsRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetPossibleActions >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleActionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::GetPossibleActionsResponse> should match 
// service_traits::MD5Sum< ::cse571_project::GetPossibleActions > 
template<>
struct MD5Sum< ::cse571_project::GetPossibleActionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetPossibleActions >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleActionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetPossibleActionsResponse> should match 
// service_traits::DataType< ::cse571_project::GetPossibleActions > 
template<>
struct DataType< ::cse571_project::GetPossibleActionsResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetPossibleActions >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleActionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_GETPOSSIBLEACTIONS_H
