// Generated by gencpp from file cse571_project/GetPossibleStates.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_GETPOSSIBLESTATES_H
#define CSE571_PROJECT_MESSAGE_GETPOSSIBLESTATES_H

#include <ros/service_traits.h>


#include <cse571_project/GetPossibleStatesRequest.h>
#include <cse571_project/GetPossibleStatesResponse.h>


namespace cse571_project
{

struct GetPossibleStates
{

typedef GetPossibleStatesRequest Request;
typedef GetPossibleStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPossibleStates
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::GetPossibleStates > {
  static const char* value()
  {
    return "ad5e6ede9037ccf3c74ff16323c7ca34";
  }

  static const char* value(const ::cse571_project::GetPossibleStates&) { return value(); }
};

template<>
struct DataType< ::cse571_project::GetPossibleStates > {
  static const char* value()
  {
    return "cse571_project/GetPossibleStates";
  }

  static const char* value(const ::cse571_project::GetPossibleStates&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::GetPossibleStatesRequest> should match 
// service_traits::MD5Sum< ::cse571_project::GetPossibleStates > 
template<>
struct MD5Sum< ::cse571_project::GetPossibleStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetPossibleStates >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetPossibleStatesRequest> should match 
// service_traits::DataType< ::cse571_project::GetPossibleStates > 
template<>
struct DataType< ::cse571_project::GetPossibleStatesRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetPossibleStates >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::GetPossibleStatesResponse> should match 
// service_traits::MD5Sum< ::cse571_project::GetPossibleStates > 
template<>
struct MD5Sum< ::cse571_project::GetPossibleStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetPossibleStates >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetPossibleStatesResponse> should match 
// service_traits::DataType< ::cse571_project::GetPossibleStates > 
template<>
struct DataType< ::cse571_project::GetPossibleStatesResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetPossibleStates >::value();
  }
  static const char* value(const ::cse571_project::GetPossibleStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_GETPOSSIBLESTATES_H
