// Generated by gencpp from file cse571_project/GetReward.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_GETREWARD_H
#define CSE571_PROJECT_MESSAGE_GETREWARD_H

#include <ros/service_traits.h>


#include <cse571_project/GetRewardRequest.h>
#include <cse571_project/GetRewardResponse.h>


namespace cse571_project
{

struct GetReward
{

typedef GetRewardRequest Request;
typedef GetRewardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetReward
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::GetReward > {
  static const char* value()
  {
    return "5db7b1f3b0b303c537d7253bf7a2c047";
  }

  static const char* value(const ::cse571_project::GetReward&) { return value(); }
};

template<>
struct DataType< ::cse571_project::GetReward > {
  static const char* value()
  {
    return "cse571_project/GetReward";
  }

  static const char* value(const ::cse571_project::GetReward&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::GetRewardRequest> should match 
// service_traits::MD5Sum< ::cse571_project::GetReward > 
template<>
struct MD5Sum< ::cse571_project::GetRewardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetReward >::value();
  }
  static const char* value(const ::cse571_project::GetRewardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetRewardRequest> should match 
// service_traits::DataType< ::cse571_project::GetReward > 
template<>
struct DataType< ::cse571_project::GetRewardRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetReward >::value();
  }
  static const char* value(const ::cse571_project::GetRewardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::GetRewardResponse> should match 
// service_traits::MD5Sum< ::cse571_project::GetReward > 
template<>
struct MD5Sum< ::cse571_project::GetRewardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::GetReward >::value();
  }
  static const char* value(const ::cse571_project::GetRewardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::GetRewardResponse> should match 
// service_traits::DataType< ::cse571_project::GetReward > 
template<>
struct DataType< ::cse571_project::GetRewardResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::GetReward >::value();
  }
  static const char* value(const ::cse571_project::GetRewardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_GETREWARD_H
