// Generated by gencpp from file cse571_project/IsTerminalState.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_ISTERMINALSTATE_H
#define CSE571_PROJECT_MESSAGE_ISTERMINALSTATE_H

#include <ros/service_traits.h>


#include <cse571_project/IsTerminalStateRequest.h>
#include <cse571_project/IsTerminalStateResponse.h>


namespace cse571_project
{

struct IsTerminalState
{

typedef IsTerminalStateRequest Request;
typedef IsTerminalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsTerminalState
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::IsTerminalState > {
  static const char* value()
  {
    return "f7b1a4100171db94609b126295dd4151";
  }

  static const char* value(const ::cse571_project::IsTerminalState&) { return value(); }
};

template<>
struct DataType< ::cse571_project::IsTerminalState > {
  static const char* value()
  {
    return "cse571_project/IsTerminalState";
  }

  static const char* value(const ::cse571_project::IsTerminalState&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::IsTerminalStateRequest> should match 
// service_traits::MD5Sum< ::cse571_project::IsTerminalState > 
template<>
struct MD5Sum< ::cse571_project::IsTerminalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::IsTerminalState >::value();
  }
  static const char* value(const ::cse571_project::IsTerminalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::IsTerminalStateRequest> should match 
// service_traits::DataType< ::cse571_project::IsTerminalState > 
template<>
struct DataType< ::cse571_project::IsTerminalStateRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::IsTerminalState >::value();
  }
  static const char* value(const ::cse571_project::IsTerminalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::IsTerminalStateResponse> should match 
// service_traits::MD5Sum< ::cse571_project::IsTerminalState > 
template<>
struct MD5Sum< ::cse571_project::IsTerminalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::IsTerminalState >::value();
  }
  static const char* value(const ::cse571_project::IsTerminalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::IsTerminalStateResponse> should match 
// service_traits::DataType< ::cse571_project::IsTerminalState > 
template<>
struct DataType< ::cse571_project::IsTerminalStateResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::IsTerminalState >::value();
  }
  static const char* value(const ::cse571_project::IsTerminalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_ISTERMINALSTATE_H
