// Generated by gencpp from file cse571_project/RemoveBlockedEdgeMsg.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_REMOVEBLOCKEDEDGEMSG_H
#define CSE571_PROJECT_MESSAGE_REMOVEBLOCKEDEDGEMSG_H

#include <ros/service_traits.h>


#include <cse571_project/RemoveBlockedEdgeMsgRequest.h>
#include <cse571_project/RemoveBlockedEdgeMsgResponse.h>


namespace cse571_project
{

struct RemoveBlockedEdgeMsg
{

typedef RemoveBlockedEdgeMsgRequest Request;
typedef RemoveBlockedEdgeMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveBlockedEdgeMsg
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::RemoveBlockedEdgeMsg > {
  static const char* value()
  {
    return "c991829b35c0398c16705137e62ce3d7";
  }

  static const char* value(const ::cse571_project::RemoveBlockedEdgeMsg&) { return value(); }
};

template<>
struct DataType< ::cse571_project::RemoveBlockedEdgeMsg > {
  static const char* value()
  {
    return "cse571_project/RemoveBlockedEdgeMsg";
  }

  static const char* value(const ::cse571_project::RemoveBlockedEdgeMsg&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::RemoveBlockedEdgeMsgRequest> should match 
// service_traits::MD5Sum< ::cse571_project::RemoveBlockedEdgeMsg > 
template<>
struct MD5Sum< ::cse571_project::RemoveBlockedEdgeMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::cse571_project::RemoveBlockedEdgeMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::RemoveBlockedEdgeMsgRequest> should match 
// service_traits::DataType< ::cse571_project::RemoveBlockedEdgeMsg > 
template<>
struct DataType< ::cse571_project::RemoveBlockedEdgeMsgRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::cse571_project::RemoveBlockedEdgeMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::RemoveBlockedEdgeMsgResponse> should match 
// service_traits::MD5Sum< ::cse571_project::RemoveBlockedEdgeMsg > 
template<>
struct MD5Sum< ::cse571_project::RemoveBlockedEdgeMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::cse571_project::RemoveBlockedEdgeMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::RemoveBlockedEdgeMsgResponse> should match 
// service_traits::DataType< ::cse571_project::RemoveBlockedEdgeMsg > 
template<>
struct DataType< ::cse571_project::RemoveBlockedEdgeMsgResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::cse571_project::RemoveBlockedEdgeMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_REMOVEBLOCKEDEDGEMSG_H
