// Generated by gencpp from file cse571_project/ResetWorldMsg.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_RESETWORLDMSG_H
#define CSE571_PROJECT_MESSAGE_RESETWORLDMSG_H

#include <ros/service_traits.h>


#include <cse571_project/ResetWorldMsgRequest.h>
#include <cse571_project/ResetWorldMsgResponse.h>


namespace cse571_project
{

struct ResetWorldMsg
{

typedef ResetWorldMsgRequest Request;
typedef ResetWorldMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetWorldMsg
} // namespace cse571_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cse571_project::ResetWorldMsg > {
  static const char* value()
  {
    return "3c2bcf2ff0894cb3058b1bf4c8c4175a";
  }

  static const char* value(const ::cse571_project::ResetWorldMsg&) { return value(); }
};

template<>
struct DataType< ::cse571_project::ResetWorldMsg > {
  static const char* value()
  {
    return "cse571_project/ResetWorldMsg";
  }

  static const char* value(const ::cse571_project::ResetWorldMsg&) { return value(); }
};


// service_traits::MD5Sum< ::cse571_project::ResetWorldMsgRequest> should match 
// service_traits::MD5Sum< ::cse571_project::ResetWorldMsg > 
template<>
struct MD5Sum< ::cse571_project::ResetWorldMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::ResetWorldMsg >::value();
  }
  static const char* value(const ::cse571_project::ResetWorldMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::ResetWorldMsgRequest> should match 
// service_traits::DataType< ::cse571_project::ResetWorldMsg > 
template<>
struct DataType< ::cse571_project::ResetWorldMsgRequest>
{
  static const char* value()
  {
    return DataType< ::cse571_project::ResetWorldMsg >::value();
  }
  static const char* value(const ::cse571_project::ResetWorldMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cse571_project::ResetWorldMsgResponse> should match 
// service_traits::MD5Sum< ::cse571_project::ResetWorldMsg > 
template<>
struct MD5Sum< ::cse571_project::ResetWorldMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cse571_project::ResetWorldMsg >::value();
  }
  static const char* value(const ::cse571_project::ResetWorldMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cse571_project::ResetWorldMsgResponse> should match 
// service_traits::DataType< ::cse571_project::ResetWorldMsg > 
template<>
struct DataType< ::cse571_project::ResetWorldMsgResponse>
{
  static const char* value()
  {
    return DataType< ::cse571_project::ResetWorldMsg >::value();
  }
  static const char* value(const ::cse571_project::ResetWorldMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_RESETWORLDMSG_H
