// Generated by gencpp from file cse571_project/ResetWorldMsgResponse.msg
// DO NOT EDIT!


#ifndef CSE571_PROJECT_MESSAGE_RESETWORLDMSGRESPONSE_H
#define CSE571_PROJECT_MESSAGE_RESETWORLDMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cse571_project
{
template <class ContainerAllocator>
struct ResetWorldMsgResponse_
{
  typedef ResetWorldMsgResponse_<ContainerAllocator> Type;

  ResetWorldMsgResponse_()
    : success(0)  {
    }
  ResetWorldMsgResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef int32_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetWorldMsgResponse_

typedef ::cse571_project::ResetWorldMsgResponse_<std::allocator<void> > ResetWorldMsgResponse;

typedef boost::shared_ptr< ::cse571_project::ResetWorldMsgResponse > ResetWorldMsgResponsePtr;
typedef boost::shared_ptr< ::cse571_project::ResetWorldMsgResponse const> ResetWorldMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cse571_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c2bcf2ff0894cb3058b1bf4c8c4175a";
  }

  static const char* value(const ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c2bcf2ff0894cb3ULL;
  static const uint64_t static_value2 = 0x058b1bf4c8c4175aULL;
};

template<class ContainerAllocator>
struct DataType< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cse571_project/ResetWorldMsgResponse";
  }

  static const char* value(const ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 success\n\
";
  }

  static const char* value(const ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetWorldMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cse571_project::ResetWorldMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int32_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSE571_PROJECT_MESSAGE_RESETWORLDMSGRESPONSE_H
